server:
  port: 8123
  servlet:
    #    指定后端接口路径
    #    localhost:8080/api
    context-path: /api
    # 2.
    session:
      # cookie 30 天过期
      #与spring-session-data-redis 库 和  spring.store-type: redis一起使用
      cookie:
        max-age: 2592000

spring:
  #指定spring应用名称(可选)
  application:
    name: jige-picture-backend
    #    数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jige_picture
    username: root
    password: abc123
  #    指定生效的配置文件
  profiles:
    active: local
  servlet:
    multipart:
      #      最大可上传的文件大小
      max-file-size: 10MB
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # session 配置
  session:
    store-type: redis
    # 1. session 30 天过期，1天24小时，1小时60分钟，1分钟60秒
    timeout: 2592000



mybatis-plus:
  configuration:
    #  开启驼峰命名
    map-underscore-to-camel-case: false
    #    仅在开发环境打印日志，StdOut标准输出，兼容性比较好
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #      指定逻辑删除的字段
      logic-delete-field: isDelete
      #      指定逻辑删除的值是什么，若为1，则删除
      logic-delete-value: 1
      #      指定逻辑未删除的值是什么，若为0，则不删除
      logic-not-delete-value: 0

#接口文档
knife4j:
  enable: true
  openapi:
    title: 鸡哥智能协同云图库接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.jige.jigepicturebackend.controller


